"""Pydantic v2 domain model for the impact analysis graph."""

from core.types.change import Change, ChangedFile, ImpactAnalysisResult, ImpactedService
from core.types.errors import (
    AdapterError,
    ConfigurationError,
    IngestionError,
    SystemGraphError,
    ValidationError,
)
from core.types.nodes import (
    DataModel,
    DataModelKind,
    EdgeSource,
    Endpoint,
    KafkaConsumer,
    KafkaProducer,
    KafkaTopic,
    Mock,
    MockKind,
    Query,
    QueryKind,
    Suggestion,
)
from core.types.service import (
    CodeArtifact,
    ContractStatus,
    Criticality,
    Direction,
    ExternalConnection,
    LineRange,
    Service,
    TestCase,
    TestType,
)

__all__ = [
    "AdapterError",
    "Change",
    "ChangedFile",
    "CodeArtifact",
    "ConfigurationError",
    "ContractStatus",
    "Criticality",
    "DataModel",
    "DataModelKind",
    "Direction",
    "EdgeSource",
    "Endpoint",
    "ExternalConnection",
    "ImpactAnalysisResult",
    "ImpactedService",
    "IngestionError",
    "KafkaConsumer",
    "KafkaProducer",
    "KafkaTopic",
    "LineRange",
    "Mock",
    "MockKind",
    "Query",
    "QueryKind",
    "Service",
    "Suggestion",
    "SystemGraphError",
    "TestCase",
    "TestType",
    "ValidationError",
]
